-- VITAEOLOGY v2 - ESERCIZI Q2 (Settimane 14-26)
-- Tipo: ESPANSIONE - Azioni piccole e sicure

-- Settimana 14: Autoconsapevolezza
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (14, 'Lo Specchio Quotidiano', 'Autoconsapevolezza', 'autoconsapevolezza', 'Vision', 'espansione', 'base', 'Q2', 30, 'Nelle settimane passate hai osservato quando ti vedi mentre operi. Ora espanderai questa capacita con un semplice rituale quotidiano.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il leader che si osserva regolarmente", "prompt": "Ripensa ai momenti di autoconsapevolezza del Q1. Quale ti ha dato piu insight?", "instructions": "Rivedi i tuoi appunti delle prime settimane."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Creare spazio per l''osservazione", "prompt": "Cosa ti aiutava a osservarti in quei momenti?", "guiding_questions": ["Era un momento particolare della giornata?", "Eri in un luogo specifico?", "C''era un trigger?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Un momento fisso di riflessione", "prompt": "Scegli 5 minuti al giorno per osservarti.", "action_steps": ["Scegli un momento fisso", "Per 5 minuti, chiediti: come ho operato oggi?", "Scrivi una frase sola"]}'::jsonb, 'Diario di 7 giorni con una frase di auto-osservazione al giorno', ARRAY['Il rituale sta diventando naturale?', 'Cosa noto che prima mi sfuggiva?', 'Come cambia la mia giornata?'], 'Anche 3 giorni su 7 sono un successo.');

-- Settimana 15: Resilienza
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (15, 'Rimbalzare', 'Resilienza', 'resilienza', 'Adaptation', 'espansione', 'base', 'Q2', 30, 'Hai gia attraversato difficolta e ne sei uscito. Questa settimana userai quella esperienza per affrontare una piccola sfida presente.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "La persona che si riprende", "prompt": "Ricorda una difficolta passata da cui ti sei ripreso completamente.", "instructions": "Non deve essere una crisi enorme."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Il tuo processo di recupero", "prompt": "Cosa ti ha aiutato a riprenderti?", "guiding_questions": ["Quanto tempo ci hai messo?", "Chi ti ha aiutato?", "Cosa hai imparato?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Applicare il pattern a oggi", "prompt": "Identifica una piccola difficolta attuale e applica lo stesso approccio.", "action_steps": ["Scegli una situazione difficile ma non critica", "Applica lo stesso processo", "Osserva cosa succede"]}'::jsonb, 'Descrizione della difficolta scelta e del processo applicato', ARRAY['Il mio processo di recupero funziona ancora?', 'Cosa posso aggiungere?', 'Come mi sento sapendo di avere un metodo?'], 'Se non hai trovato una difficolta, e un buon segno.');

-- Settimana 16: Coraggio
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (16, 'Un Piccolo Rischio', 'Coraggio', 'coraggio', 'Vision', 'espansione', 'intermedio', 'Q2', 30, 'Hai osservato il coraggio quotidiano. Ora farai un piccolo passo oltre la tua zona di comfort.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi sei quando osi", "prompt": "Ripensa ai piccoli atti di coraggio del Q1. Quale ti ha dato piu soddisfazione?", "instructions": "Cerca l''atto che ti ha fatto sentire piu vivo."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come ti prepari a osare", "prompt": "Cosa ti ha permesso di fare quel passo?", "guiding_questions": ["Ti sei preparato o e stato spontaneo?", "Avevi una via d''uscita?", "Cosa ti sei detto?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Un nuovo piccolo rischio", "prompt": "Scegli UNA azione che richiede un piccolo coraggio e falla questa settimana.", "action_steps": ["Identifica qualcosa che rimandi per timore", "Assicurati che il rischio sia gestibile", "Fallo entro 7 giorni"]}'::jsonb, 'Descrizione dell''azione scelta e come ti sei sentito', ARRAY['Era piu facile o piu difficile di quanto pensassi?', 'Cosa ho imparato su me stesso?', 'Quale sara il prossimo piccolo rischio?'], 'Se non hai fatto l''azione, quella informazione e preziosa.');

-- Settimana 17: Visione
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (17, 'Scrivere il Futuro', 'Visione', 'visione', 'Vision', 'espansione', 'intermedio', 'Q2', 35, 'Hai notato quando guardi al futuro. Ora darai forma concreta a quella visione, scrivendola.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il visionario che sei", "prompt": "Ripensa ai momenti in cui hai guardato oltre l''immediato. Cosa vedevi piu spesso?", "instructions": "Cerca temi ricorrenti nelle tue visioni."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come la tua visione prende forma", "prompt": "Quando la visione e piu chiara, cosa stai facendo?", "guiding_questions": ["Sei solo o con altri?", "E mattina, sera, weekend?", "Scrivi, parli o pensi?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Una visione scritta", "prompt": "Scrivi dove vedi la tua attivita tra 3 anni.", "action_steps": ["Trova 30 minuti di tranquillita", "Scrivi liberamente", "Includi: cosa fai, con chi, come ti senti"]}'::jsonb, 'Documento di 1-2 pagine con la visione a 3 anni', ARRAY['Scrivere ha chiarito o confuso la visione?', 'Cosa mi sorprende?', 'Cosa manca ancora?'], 'Se non sei riuscito a scrivere, prova a registrare un audio.');

-- Settimana 18: Pensiero Strategico
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (18, 'Mappa delle Conseguenze', 'Pensiero Strategico', 'pensiero-strategico', 'Vision', 'espansione', 'intermedio', 'Q2', 35, 'Hai osservato come la tua mente connette cause ed effetti. Ora userai questo potere per analizzare una decisione importante.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Lo stratega che sei", "prompt": "Ripensa alle connessioni che hai notato nel Q1. Quale si e rivelata piu accurata?", "instructions": "Cerca una previsione che si e avverata."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Il tuo processo strategico", "prompt": "Come arrivi a vedere connessioni che altri non vedono?", "guiding_questions": ["Raccogli informazioni o ti fidi dell''intuito?", "Pensi da solo o parli con altri?", "Usi strumenti?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Analisi strutturata", "prompt": "Prendi una decisione che devi prendere e mappa le conseguenze.", "action_steps": ["Scegli una decisione importante ma non urgente", "Per ogni opzione scrivi le conseguenze a cascata", "Analizza almeno 3 livelli"]}'::jsonb, 'Mappa scritta delle conseguenze per una decisione reale', ARRAY['L''analisi ha cambiato la mia scelta?', 'Quali conseguenze non avevo considerato?', 'Quanto tempo mi serve?'], 'Se la mappa ti sembra incompleta, e normale.');

-- Settimana 19: Empatia
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (19, 'Mettersi nei Panni', 'Empatia', 'empatia', 'Relations', 'espansione', 'intermedio', 'Q2', 30, 'Hai osservato quando senti le emozioni degli altri. Ora userai questa capacita intenzionalmente.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi sente l''altro", "prompt": "Con chi ti viene piu naturale l''empatia?", "instructions": "Pensa a qualcuno con cui ti connetti facilmente a livello emotivo."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come attivi l''empatia", "prompt": "Cosa fai quando vuoi capire come si sente qualcuno?", "guiding_questions": ["Guardi, ascolti, o entrambi?", "Fai domande o aspetti?", "Ti viene naturale o devi sforzarti?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Empatia intenzionale", "prompt": "Scegli una persona con cui hai difficolta e prova a capire come si sente.", "action_steps": ["Identifica qualcuno con cui la relazione e tesa", "Chiediti: cosa sta vivendo?", "Prova a vedere dai suoi occhi"]}'::jsonb, 'Riflessione scritta sulla prospettiva dell''altra persona', ARRAY['Ho scoperto qualcosa che non avevo considerato?', 'Come cambia la relazione?', 'E stato difficile?'], 'Se non sei riuscito, nota cosa ti ha bloccato.');

-- Settimana 20: Comunicazione
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (20, 'Messaggio Chiaro', 'Comunicazione', 'comunicazione', 'Relations', 'espansione', 'intermedio', 'Q2', 30, 'Hai notato quando la tua comunicazione crea vera comprensione. Ora applicherai consapevolmente cio che funziona.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il comunicatore efficace", "prompt": "Qual e stata la tua comunicazione piu efficace del Q1?", "instructions": "Ripensa a un momento in cui l''altro ha capito perfettamente."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Il tuo stile quando funziona", "prompt": "Cosa caratterizza la tua comunicazione quando e efficace?", "guiding_questions": ["Usi esempi?", "Verifichi la comprensione?", "Adatti il linguaggio?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Comunicazione preparata", "prompt": "Prepara e fai una comunicazione importante usando cio che funziona.", "action_steps": ["Scegli un messaggio importante", "Preparalo usando i tuoi pattern efficaci", "Fai la comunicazione e osserva"]}'::jsonb, 'Descrizione del messaggio preparato e del risultato', ARRAY['La preparazione ha fatto differenza?', 'Cosa aggiungero alla prossima?', 'Come posso applicare questo quotidianamente?'], 'Se non e andata come speravi, analizza cosa non ha funzionato.');

-- Settimana 21: Fiducia
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (21, 'Gesto di Fiducia', 'Fiducia', 'fiducia', 'Relations', 'espansione', 'intermedio', 'Q2', 30, 'Hai osservato come costruisci fiducia. Ora farai un gesto intenzionale per rafforzare una relazione.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi costruisce ponti", "prompt": "Quale relazione professionale vorresti rafforzare?", "instructions": "Pensa a qualcuno con cui la relazione potrebbe essere migliore."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come hai costruito fiducia in passato", "prompt": "Qual e stato il gesto che ha fatto la differenza?", "guiding_questions": ["Era un gesto grande o piccolo?", "Era pianificato o spontaneo?", "Quanto tempo dopo hai visto l''effetto?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Un gesto concreto", "prompt": "Fai un gesto di fiducia verso la persona scelta.", "action_steps": ["Scegli un gesto appropriato", "Fallo senza aspettarti nulla", "Osserva cosa succede"]}'::jsonb, 'Descrizione del gesto fatto e delle tue osservazioni', ARRAY['Come mi sono sentito?', 'Ho notato cambiamenti?', 'Cosa farei diversamente?'], 'Se non hai fatto il gesto, chiediti cosa ti ha fermato.');

-- Settimana 22: Ascolto
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (22, 'Conversazione Profonda', 'Ascolto', 'ascolto', 'Relations', 'espansione', 'intermedio', 'Q2', 30, 'Hai notato quando ascolti veramente. Ora creerai intenzionalmente uno spazio di ascolto profondo.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "L''ascoltatore presente", "prompt": "Con chi ti viene piu naturale ascoltare profondamente?", "instructions": "Pensa a conversazioni dove eri totalmente presente."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Le condizioni dell''ascolto vero", "prompt": "Cosa ti aiuta ad ascoltare senza distrarti?", "guiding_questions": ["Dove avvengono le migliori conversazioni?", "Quanto tempo serve?", "Cosa fai con le distrazioni?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Creare spazio per l''ascolto", "prompt": "Organizza una conversazione dove il tuo unico obiettivo e ascoltare.", "action_steps": ["Scegli qualcuno che ha bisogno di essere ascoltato", "Crea le condizioni giuste", "Ascolta senza dare consigli"]}'::jsonb, 'Riflessione sulla conversazione', ARRAY['Come si e sentita l''altra persona?', 'Quanto e stato difficile non dare consigli?', 'Cosa ho imparato?'], 'Se non hai fatto la conversazione, nota cosa ti ha impedito.');

-- Settimana 23: Decisionalita
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (23, 'La Decisione Sospesa', 'Decisionalita', 'decisionalita', 'Action', 'espansione', 'intermedio', 'Q2', 30, 'Hai osservato come decidi. Ora affronterai una decisione che stai rimandando.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi decide con chiarezza", "prompt": "C''e una decisione che stai rimandando? Da quanto tempo?", "instructions": "Identifica una decisione che dovresti prendere."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa blocca questa decisione", "prompt": "Perche non hai ancora deciso?", "guiding_questions": ["Ti mancano informazioni?", "Temi le conseguenze?", "Aspetti che altri decidano?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Decidere comunque", "prompt": "Prendi la decisione entro questa settimana.", "action_steps": ["Dai una deadline: entro venerdi decido", "Accetta che non avrai mai tutte le informazioni", "Decidi e comunica"]}'::jsonb, 'La decisione presa e come ti sei sentito dopo', ARRAY['Era cosi difficile come pensavo?', 'Cosa mi ha fatto decidere?', 'Come mi sento ora?'], 'Se non hai deciso, chiediti cosa succederebbe se non decidessi mai.');

-- Settimana 24: Responsabilita
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (24, 'Prendersi Carico', 'Responsabilita', 'responsabilita', 'Action', 'espansione', 'intermedio', 'Q2', 30, 'Hai notato dove ti assumi ownership naturalmente. Ora lo farai in un''area nuova.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi si assume ownership", "prompt": "C''e qualcosa nella tua attivita che nessuno sta gestendo?", "instructions": "Cerca un''area orfana."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche non l''hai gia preso in carico", "prompt": "Cosa ti ha impedito di assumertene la responsabilita?", "guiding_questions": ["Non e il tuo ruolo?", "Richiede tempo?", "Aspetti che altri lo facciano?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Ownership volontaria", "prompt": "Assumi ownership di quell''area orfana.", "action_steps": ["Dichiara: questo lo gestisco io", "Fai un primo passo entro 48 ore", "Comunica agli altri"]}'::jsonb, 'Descrizione dell''area presa in carico e del primo passo', ARRAY['Come hanno reagito gli altri?', 'Mi sento sovraccarico o energizzato?', 'Era davvero necessario?'], 'Se non hai preso ownership, nota se il blocco era pratico o emotivo.');

-- Settimana 25: Innovazione
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (25, 'Esplorare il Nuovo', 'Innovazione', 'innovazione', 'Action', 'espansione', 'intermedio', 'Q2', 35, 'L''innovazione inizia con la curiosita verso il nuovo. Questa settimana esplorerai qualcosa al di fuori della tua routine.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "L''esploratore che sei", "prompt": "Quando e stata l''ultima volta che hai provato qualcosa di completamente nuovo?", "instructions": "Cerca un momento in cui hai sperimentato."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come ti avvicini al nuovo", "prompt": "Cosa ti serve per provare qualcosa di nuovo?", "guiding_questions": ["Hai bisogno di garanzie?", "Preferisci studiare prima o provare?", "Lo fai da solo o con altri?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Un esperimento sicuro", "prompt": "Prova qualcosa di nuovo nel tuo lavoro.", "action_steps": ["Scegli qualcosa di piccolo ma diverso", "Non deve funzionare - e un esperimento", "Osserva cosa impari"]}'::jsonb, 'Descrizione dell''esperimento e cosa hai imparato', ARRAY['L''esperimento e stato utile?', 'Cosa provero la prossima volta?', 'La novita mi stimola o mi stressa?'], 'Se non hai provato nulla di nuovo, nota cosa ti ha fermato.');

-- Settimana 26: Perseveranza
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (26, 'Continuare Nonostante', 'Perseveranza', 'perseveranza', 'Action', 'espansione', 'intermedio', 'Q2', 30, 'La perseveranza si rivela quando continuiamo nonostante le difficolta. Questa settimana rafforzerai un impegno che sta vacillando.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi continua", "prompt": "C''e un progetto o impegno che stai per abbandonare?", "instructions": "Cerca qualcosa che ha iniziato con entusiasmo ma sta perdendo energia."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa ti sta facendo mollare", "prompt": "Perche stai perdendo motivazione?", "guiding_questions": ["I risultati tardano?", "E piu difficile del previsto?", "Altre priorita ti distraggono?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Riaccendere l''impegno", "prompt": "Rilancia l''impegno con un''azione concreta.", "action_steps": ["Ricorda perche hai iniziato", "Fai un passo avanti entro 48 ore", "Condividi l''impegno rinnovato"]}'::jsonb, 'Descrizione del rilancio', ARRAY['Cosa mi ha fatto continuare?', 'Il progetto meritava di essere salvato?', 'Come evitero questo in futuro?'], 'Se hai deciso di abbandonare, va bene. A volte la vera saggezza e mollare.');
