-- VITAEOLOGY v2 - ESERCIZI Q3 (Settimane 27-39)
-- Tipo: SFIDA - Azioni che richiedono coraggio

-- Settimana 27: Efficienza
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (27, 'Fare di Piu con Meno', 'Efficienza', 'efficienza', 'Action', 'sfida', 'intermedio', 'Q3', 35, 'L''efficienza vera significa ottenere risultati eccellenti con risorse limitate. Questa settimana affronterai una sfida di ottimizzazione.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "L''ottimizzatore", "prompt": "Dove nella tua attivita sprechi piu risorse?", "instructions": "Sii onesto. Cerca un processo che consuma piu di quanto produce."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche lo spreco continua", "prompt": "Cosa ti impedisce di eliminare quello spreco?", "guiding_questions": ["E abitudine?", "Richiede una decisione difficile?", "Coinvolge altre persone?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Eliminare uno spreco", "prompt": "Elimina o riduci drasticamente quello spreco questa settimana.", "action_steps": ["Scegli lo spreco piu grande", "Decidi: eliminare, ridurre o delegare", "Agisci entro 7 giorni"]}'::jsonb, 'Descrizione dello spreco eliminato e delle risorse liberate', ARRAY['E stato difficile quanto pensavo?', 'Quali altre inefficienze vedo ora?', 'Come evitero che si ricreino?'], 'Se non hai eliminato lo spreco, chiediti se e davvero spreco.');

-- Settimana 28: Delega
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (28, 'Lasciare Andare', 'Delega', 'delega', 'Relations', 'sfida', 'avanzato', 'Q3', 40, 'Delegare veramente significa fidarsi che altri possano fare. Questa settimana affronterai una delega significativa.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi fa crescere altri", "prompt": "C''e qualcosa che fai tu che altri potrebbero fare?", "instructions": "Cerca un compito che tieni per te anche se non e necessario."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa ti impedisce di delegare", "prompt": "Perche continui a farlo tu?", "guiding_questions": ["Pensi che nessuno lo farebbe bene?", "Richiede piu tempo spiegare?", "Hai paura di perdere controllo?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Una delega vera", "prompt": "Delega quel compito completamente.", "action_steps": ["Scegli a chi delegare", "Spiega il risultato atteso, non il come", "Lascia che lo facciano a modo loro"]}'::jsonb, 'Descrizione della delega: cosa, a chi, come e andata', ARRAY['Ho resistito alla tentazione di interferire?', 'Il risultato e stato accettabile?', 'Cosa ho imparato sulla persona?'], 'Se non hai delegato o hai ripreso il controllo, nota cosa ti ha fatto paura.');

-- Settimana 29: Feedback
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (29, 'La Verita Utile', 'Feedback', 'feedback', 'Relations', 'sfida', 'avanzato', 'Q3', 35, 'Il feedback autentico e un dono raro. Questa settimana darai un feedback importante che stai rimandando.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi dice la verita con cura", "prompt": "C''e un feedback che dovresti dare a qualcuno ma non hai ancora dato?", "instructions": "Cerca qualcosa di importante che l''altro dovrebbe sapere per migliorare."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche non lo hai ancora dato", "prompt": "Cosa ti trattiene dal dare quel feedback?", "guiding_questions": ["Temi la reazione?", "Non sai come dirlo?", "Dubiti che sia il tuo ruolo?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Feedback con coraggio", "prompt": "Dai quel feedback questa settimana.", "action_steps": ["Prepara: situazione, comportamento, impatto", "Scegli momento e luogo appropriati", "Dillo con rispetto ma senza edulcorare"]}'::jsonb, 'Descrizione del feedback dato e della reazione', ARRAY['Come mi sono sentito dopo?', 'L''altro ha apprezzato o si e offeso?', 'Cosa faro diversamente?'], 'Se non hai dato il feedback, chiediti se era davvero utile darlo.');

-- Settimana 30: Sviluppo Team
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (30, 'Far Crescere Qualcuno', 'Sviluppo Team', 'sviluppo-team', 'Adaptation', 'sfida', 'avanzato', 'Q3', 40, 'Il vero leader si misura dalle persone che fa crescere. Questa settimana investirai nella crescita di qualcuno.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi sviluppa altri", "prompt": "Chi nel tuo team ha potenziale inespresso?", "instructions": "Cerca qualcuno che potrebbe fare di piu."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa serve per farli crescere", "prompt": "Di cosa ha bisogno quella persona per sbloccarsi?", "guiding_questions": ["Ha bisogno di competenze tecniche?", "Ha bisogno di fiducia in se stesso?", "Ha bisogno di opportunita?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Un piano di sviluppo", "prompt": "Crea e inizia un mini-piano di sviluppo.", "action_steps": ["Identifica UNA cosa su cui lavorare", "Parla con la persona", "Dagli una prima opportunita"]}'::jsonb, 'Piano di sviluppo sintetico e descrizione della prima azione', ARRAY['Come ha reagito la persona?', 'Ho dedicato abbastanza tempo?', 'Quanto sono investito nella sua crescita?'], 'Se non hai iniziato il piano, nota se il blocco e tempo, energia o convinzione.');

-- Settimana 31: Adattabilita
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (31, 'Cambiare Rotta', 'Adattabilita', 'adattabilita', 'Adaptation', 'sfida', 'avanzato', 'Q3', 35, 'L''adattabilita vera significa cambiare approccio quando i dati lo richiedono. Questa settimana affronterai un cambiamento necessario.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi sa cambiare", "prompt": "C''e qualcosa che stai facendo che non funziona piu?", "instructions": "Cerca un approccio che continui a usare per abitudine."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche non hai ancora cambiato", "prompt": "Cosa ti tiene legato a quell''approccio?", "guiding_questions": ["E l''investimento gia fatto?", "E paura del nuovo?", "E orgoglio?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Cambiare veramente", "prompt": "Cambia quell''approccio questa settimana.", "action_steps": ["Ammetti che non funziona", "Identifica un''alternativa", "Implementa il cambiamento"]}'::jsonb, 'Descrizione del cambiamento fatto e delle prime reazioni', ARRAY['E stato liberatorio o doloroso?', 'Come hanno reagito gli altri?', 'Cosa mi insegna sulla mia resistenza?'], 'Se non hai cambiato, sii onesto sul perche.');

-- Settimana 32: Apprendimento Continuo
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (32, 'Tornare Studente', 'Apprendimento Continuo', 'apprendimento', 'Adaptation', 'sfida', 'intermedio', 'Q3', 40, 'L''apprendimento continuo significa ammettere di non sapere. Questa settimana imparerai qualcosa di completamente nuovo.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "L''eterno studente", "prompt": "Cosa dovresti imparare che continui a rimandare?", "instructions": "Cerca una competenza che sarebbe utile."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche non lo hai ancora imparato", "prompt": "Cosa ti impedisce di dedicare tempo all''apprendimento?", "guiding_questions": ["Non e urgente?", "Ti senti troppo vecchio?", "Deleghi a chi sa gia?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Iniziare ad imparare", "prompt": "Inizia ad imparare quella cosa.", "action_steps": ["Scegli UNA cosa da imparare", "Dedica almeno 2 ore questa settimana", "Accetta di essere principiante"]}'::jsonb, 'Descrizione di cosa hai iniziato a imparare e come ti sei sentito', ARRAY['Com''e essere principiante?', 'Ho sottovalutato o sopravvalutato la difficolta?', 'Voglio continuare?'], 'Se non hai iniziato, nota cosa ti ha fermato.');

-- Settimana 33: Inclusione
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (33, 'Valorizzare le Differenze', 'Inclusione', 'inclusione', 'Adaptation', 'sfida', 'avanzato', 'Q3', 35, 'L''inclusione vera significa cercare attivamente prospettive diverse. Questa settimana includerai una voce che di solito escludi.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi include", "prompt": "Chi nel tuo ambiente ha prospettive diverse che tendi a ignorare?", "instructions": "Cerca qualcuno con una prospettiva che non consideri abbastanza."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche escludi quella voce", "prompt": "Cosa ti fa ignorare quella prospettiva?", "guiding_questions": ["E scomoda?", "Non la capisci?", "La consideri meno valida?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Includere attivamente", "prompt": "Chiedi attivamente quella prospettiva.", "action_steps": ["Identifica la persona", "Chiedi il suo punto di vista su una questione importante", "Ascolta senza difenderti"]}'::jsonb, 'Descrizione della conversazione e cosa hai imparato', ARRAY['Ho scoperto qualcosa di utile?', 'E stato difficile ascoltare senza giudicare?', 'Come cambiero il mio approccio?'], 'Se non hai cercato quella prospettiva, nota cosa ti ha fermato.');

-- Settimana 34: Orientamento ai Risultati
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (34, 'Dal Sogno al Fatto', 'Orientamento ai Risultati', 'orientamento-risultati', 'Adaptation', 'sfida', 'avanzato', 'Q3', 40, 'L''orientamento ai risultati significa tradurre visione in outcome concreti. Questa settimana trasformerai un''idea in un risultato.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi produce risultati", "prompt": "C''e un''idea o progetto che resta sempre in fase di pianificazione?", "instructions": "Cerca qualcosa che pensi, parli, pianifichi... ma non fai mai."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa blocca l''esecuzione", "prompt": "Perche quell''idea non diventa mai realta?", "guiding_questions": ["La pianificazione ti protegge dal fallimento?", "Aspetti le condizioni perfette?", "Ti piace piu pensare che fare?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Un risultato concreto", "prompt": "Produci un risultato tangibile da quell''idea.", "action_steps": ["Scegli la versione piu piccola possibile", "Definisci un risultato misurabile", "Producilo entro 7 giorni"]}'::jsonb, 'Il risultato prodotto e cosa hai imparato', ARRAY['E meglio o peggio di come lo immaginavo?', 'Cosa serve per andare avanti?', 'Il risultato ha cambiato l''idea?'], 'Se non hai prodotto nulla, nota cosa ti ha fermato.');

-- Settimana 35: Autoconsapevolezza (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (35, 'Chiedere agli Altri', 'Autoconsapevolezza', 'autoconsapevolezza', 'Vision', 'sfida', 'avanzato', 'Q3', 40, 'La vera autoconsapevolezza include vedere come gli altri ti vedono. Questa settimana chiederai feedback su te stesso.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi si conosce attraverso gli altri", "prompt": "Come pensi che gli altri ti vedano come leader?", "instructions": "Scrivi come credi di essere percepito. Poi preparati a verificare."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "La tua percezione vs realta", "prompt": "Quando hai chiesto a qualcuno come ti vede?", "guiding_questions": ["Temi il giudizio?", "Pensi di saperlo gia?", "Non ti importa cosa pensano?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Feedback su di te", "prompt": "Chiedi a 2-3 persone: come mi vedi come leader?", "action_steps": ["Scegli persone di cui ti fidi", "Chiedi: qual e la mia forza? Cosa potrei migliorare?", "Ascolta senza difenderti"]}'::jsonb, 'Sintesi del feedback ricevuto e confronto con la tua percezione', ARRAY['C''erano sorprese?', 'Sono stato difensivo?', 'Cosa faro con questo feedback?'], 'Se non hai chiesto feedback, nota cosa ti ha fermato.');

-- Settimana 36: Coraggio (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (36, 'La Conversazione Difficile', 'Coraggio', 'coraggio', 'Vision', 'sfida', 'avanzato', 'Q3', 40, 'Il coraggio del leader si mostra nelle conversazioni che preferirebbe evitare. Questa settimana affronterai una conversazione difficile.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi affronta le situazioni difficili", "prompt": "C''e una conversazione che stai evitando?", "instructions": "Cerca una conversazione importante che rimandi."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche la eviti", "prompt": "Cosa temi da quella conversazione?", "guiding_questions": ["Conflitto?", "Ferire l''altro?", "Scoprire qualcosa che non vuoi sapere?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Affrontare con coraggio", "prompt": "Fai quella conversazione questa settimana.", "action_steps": ["Preparati: cosa vuoi dire e ottenere", "Scegli momento e luogo appropriati", "Affronta con rispetto ma senza fuggire"]}'::jsonb, 'Descrizione della conversazione e cosa e emerso', ARRAY['Era cosi terribile come pensavo?', 'Cosa e cambiato dopo?', 'Avrei dovuto farla prima?'], 'Se non hai fatto la conversazione, chiediti se e davvero necessaria.');

-- Settimana 37: Valori (secondo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (37, 'Vivere i Valori', 'Valori', 'valori', 'Vision', 'sfida', 'avanzato', 'Q3', 35, 'I valori veri si dimostrano quando costa mantenerli. Questa settimana onorerai un valore anche se scomodo.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi vive i propri valori", "prompt": "Qual e il tuo valore piu importante che a volte tradisci per convenienza?", "instructions": "Sii onesto: tutti abbiamo momenti in cui compromettiamo i nostri valori."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Quando e perche tradisci quel valore", "prompt": "In quali situazioni metti da parte quel valore?", "guiding_questions": ["Sotto pressione?", "Per soldi?", "Per evitare conflitti?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Onorare il valore", "prompt": "Quando si presenta l''occasione, scegli il valore.", "action_steps": ["Identifica una situazione probabile", "Decidi in anticipo: scegliero il valore", "Quando accade, mantieni la promessa"]}'::jsonb, 'Descrizione della situazione e della scelta fatta', ARRAY['Quanto e costato?', 'Ne e valsa la pena?', 'Come mi sento avendo mantenuto il valore?'], 'Se non si e presentata l''occasione, mantieni la consapevolezza.');

-- Settimana 38: Disciplina (secondo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (38, '21 Giorni', 'Disciplina', 'disciplina', 'Action', 'sfida', 'avanzato', 'Q3', 30, 'La disciplina si costruisce con la ripetizione. Questa settimana inizierai un''abitudine che richiede costanza quotidiana.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi costruisce abitudini", "prompt": "Quale abitudine positiva vorresti avere ma non riesci a mantenere?", "instructions": "Cerca qualcosa che hai provato ma hai sempre mollato."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche le abitudini non tengono", "prompt": "Cosa ti ha fatto mollare le altre volte?", "guiding_questions": ["Troppo ambizioso?", "Nessuna conseguenza se salti?", "Mancanza di reminder?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Iniziare i 21 giorni", "prompt": "Inizia un''abitudine quotidiana e mantienila per 7 giorni.", "action_steps": ["Scegli un''abitudine piccola", "Collegala a qualcosa che gia fai", "Non saltare nemmeno un giorno"]}'::jsonb, 'Diario dei 7 giorni', ARRAY['Qual e stato il giorno piu difficile?', 'Sta diventando piu facile?', 'Continuero oltre i 7 giorni?'], 'Se hai saltato giorni, non ricominciare da zero - continua.');

-- Settimana 39: Creativita (secondo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (39, 'Pensiero Laterale', 'Creativita', 'creativita', 'Vision', 'sfida', 'avanzato', 'Q3', 40, 'La creativita si amplifica quando la sfidiamo intenzionalmente. Questa settimana risolverai un problema in modo non convenzionale.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il pensatore laterale", "prompt": "Qual e un problema nel tuo business che tutti affrontano nello stesso modo?", "instructions": "Cerca un problema dove la soluzione standard e scontata."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Perche usi la soluzione standard", "prompt": "Cosa ti impedisce di provare approcci diversi?", "guiding_questions": ["E troppo rischioso?", "Non hai tempo per sperimentare?", "Funziona abbastanza bene cosi?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Una soluzione non convenzionale", "prompt": "Affronta quel problema in modo completamente diverso.", "action_steps": ["Elenca 5 modi folli per risolverlo", "Scegli il meno folle tra i folli", "Prova quell''approccio"]}'::jsonb, 'Descrizione del problema, della soluzione e del risultato', ARRAY['Ha funzionato?', 'Anche se no, cosa ho imparato?', 'Usero piu spesso il pensiero laterale?'], 'Se non hai provato un approccio diverso, nota cosa ti ha fermato.');
