-- VITAEOLOGY v2 - ESERCIZI Q4 (Settimane 40-52)
-- Tipo: INTEGRAZIONE - Consolidamento

-- Settimana 40: Visione (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (40, 'La Visione Condivisa', 'Visione', 'visione', 'Vision', 'integrazione', 'avanzato', 'Q4', 45, 'La visione del leader diventa potente quando e condivisa. Questa settimana comunicherai la tua visione al team.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il visionario che ispira", "prompt": "Riprendi la visione scritta nella settimana 17. E ancora valida?", "instructions": "Rivedi il documento di visione che hai scritto. Aggiornalo se necessario."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come condividi la visione", "prompt": "Quanto del tuo team conosce la tua visione?", "guiding_questions": ["L''hai mai comunicata esplicitamente?", "Pensano che sia anche la loro visione?", "Cosa sanno del futuro che immagini?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Comunicare e co-creare la visione", "prompt": "Condividi la tua visione con il team e raccogli il loro input.", "action_steps": ["Prepara una presentazione semplice", "Condividila in un momento dedicato", "Chiedi: cosa aggiungereste?"]}'::jsonb, 'Documento della visione condivisa', ARRAY['Come hanno reagito?', 'La visione e piu forte con il loro contributo?', 'Cosa devo fare per renderla realta?'], 'Se non hai condiviso, chiediti: temi il giudizio?');

-- Settimana 41: Pensiero Strategico (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (41, 'Il Piano d''Azione', 'Pensiero Strategico', 'pensiero-strategico', 'Vision', 'integrazione', 'avanzato', 'Q4', 50, 'Il pensiero strategico si completa quando diventa piano d''azione. Questa settimana trasformerai la visione in strategia.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Lo stratega che esegue", "prompt": "Della visione condivisa, qual e l''elemento piu importante da realizzare nel prossimo anno?", "instructions": "Scegli UN obiettivo strategico dalla visione."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Come trasformi idee in piani", "prompt": "Qual e il tuo processo per passare da idea a piano?", "guiding_questions": ["Parti dai risultati o dalle azioni?", "Coinvolgi altri nella pianificazione?", "Come gestisci l''incertezza?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Piano strategico", "prompt": "Crea un piano per quell''obiettivo.", "action_steps": ["Definisci il risultato misurabile a 12 mesi", "Identifica i 3-5 milestone trimestrali", "Per il prossimo trimestre, dettaglia le azioni"]}'::jsonb, 'Piano strategico a 12 mesi per un obiettivo', ARRAY['Il piano e realistico?', 'Cosa potrebbe farlo fallire?', 'Cosa devo iniziare subito?'], 'Se non hai creato il piano, nota cosa ti ha fermato.');

-- Settimana 42: Responsabilita (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (42, 'Accountability', 'Responsabilita', 'responsabilita', 'Action', 'integrazione', 'avanzato', 'Q4', 35, 'La responsabilita matura include rendere conto agli altri. Questa settimana creerai un sistema di accountability.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi rende conto", "prompt": "A chi rendi conto dei tuoi impegni?", "instructions": "Se nessuno ti chiede conto, nota come questo influenza l''esecuzione."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Il tuo rapporto con l''accountability", "prompt": "Come reagisci quando qualcuno ti chiede conto?", "guiding_questions": ["Ti infastidisce o ti motiva?", "Cerchi scuse o assumi responsabilita?", "Preferisci non avere nessuno che ti controlli?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Creare accountability", "prompt": "Crea un sistema di accountability per il piano strategico.", "action_steps": ["Scegli una persona a cui rendere conto", "Definisci cosa e quando riporterai", "Fai il primo report questa settimana"]}'::jsonb, 'Descrizione del sistema di accountability creato', ARRAY['Chi ho scelto e perche?', 'Come mi sento a rendere conto?', 'Questo mi aiutera a eseguire?'], 'Se non hai creato accountability, chiediti: preferisci la liberta di non rendere conto?');

-- Settimana 43: Comunicazione (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (43, 'Il Tuo Stile di Comunicazione', 'Comunicazione', 'comunicazione', 'Relations', 'integrazione', 'avanzato', 'Q4', 40, 'Ogni leader ha uno stile di comunicazione. Questa settimana codificherai e raffinerai il tuo.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il comunicatore consapevole", "prompt": "Come descriveresti il tuo stile di comunicazione in 3 parole?", "instructions": "Pensa a come ti descriverebbero gli altri."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Punti di forza e debolezza", "prompt": "Quando la tua comunicazione funziona meglio e quando fallisce?", "guiding_questions": ["Con che tipo di persone comunichi meglio?", "In quali situazioni fai fatica?", "Cosa ti dicono gli altri?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Sviluppare lo stile", "prompt": "Identifica UN aspetto del tuo stile da migliorare.", "action_steps": ["Scegli una debolezza specifica", "Definisci come la migliorerai", "Pratica intenzionalmente questa settimana"]}'::jsonb, 'Descrizione del tuo stile e del miglioramento scelto', ARRAY['Ho notato miglioramenti?', 'Cosa devo continuare a praticare?', 'Il mio stile e autentico?'], 'Se non hai identificato miglioramenti, chiedi feedback specifico.');

-- Settimana 44: Fiducia (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (44, 'La Rete di Fiducia', 'Fiducia', 'fiducia', 'Relations', 'integrazione', 'avanzato', 'Q4', 40, 'La fiducia si costruisce in rete. Questa settimana mapperai e rafforzerai la tua rete di fiducia.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il costruttore di reti", "prompt": "Chi sono le persone chiave nella tua rete professionale?", "instructions": "Fai una lista delle relazioni importanti e valuta il livello di fiducia."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Dove la rete e debole", "prompt": "Dove ci sono buchi nella tua rete di fiducia?", "guiding_questions": ["Ci sono relazioni importanti ma fragili?", "Mancano relazioni in aree chiave?", "Qualche relazione si e deteriorata?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Rafforzare la rete", "prompt": "Scegli 2-3 relazioni da rafforzare e agisci.", "action_steps": ["Identifica relazioni da coltivare", "Per ognuna, pianifica un''azione di rafforzamento", "Eseguila questa settimana"]}'::jsonb, 'Mappa delle relazioni di fiducia e azioni intraprese', ARRAY['La mia rete e abbastanza forte?', 'Dove devo investire di piu?', 'Come mantenerle nel tempo?'], 'Se non hai mappato o agito, nota il blocco.');

-- Settimana 45: Empatia (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (45, 'Leadership Empatica', 'Empatia', 'empatia', 'Relations', 'integrazione', 'avanzato', 'Q4', 40, 'L''empatia nel leader significa considerare l''impatto sulle persone nelle decisioni. Questa settimana integrerai l''empatia nel processo decisionale.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il leader empatico", "prompt": "Quando prendi decisioni, quanto consideri l''impatto emotivo?", "instructions": "Pensa a decisioni recenti. L''impatto sulle persone era un fattore?"}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Empatia nelle decisioni", "prompt": "Come potresti integrare meglio l''empatia?", "guiding_questions": ["Consulti le persone coinvolte?", "Comunichi le decisioni con attenzione?", "Rivedi le decisioni se l''impatto e troppo duro?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Decisione empatica", "prompt": "Per una decisione importante, considera esplicitamente l''impatto sulle persone.", "action_steps": ["Identifica una decisione da prendere", "Mappa l''impatto su ogni persona", "Considera come comunicare e supportare"]}'::jsonb, 'Descrizione della decisione e dell''analisi empatica', ARRAY['L''empatia ha cambiato la decisione?', 'Le persone hanno notato l''attenzione?', 'Come bilancio empatia e risultati?'], 'Se non hai applicato questo processo, e questione di tempo o abitudine?');

-- Settimana 46: Delega (secondo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (46, 'Sistema di Delega', 'Delega', 'delega', 'Relations', 'integrazione', 'avanzato', 'Q4', 45, 'La delega efficace richiede un sistema, non solo atti singoli. Questa settimana creerai il tuo sistema di delega.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il delegatore sistematico", "prompt": "Cosa fai ancora tu che altri potrebbero fare? Fai una lista.", "instructions": "Elenca tutto cio che fai regolarmente. Segna cosa solo tu puoi fare."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa deleghi e cosa no", "prompt": "C''e un pattern in cio che deleghi vs cio che tieni?", "guiding_questions": ["Tieni le cose difficili o le facili?", "Tieni cio che ti piace?", "Deleghi solo quando sei sommerso?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Piano di delega", "prompt": "Crea un piano per delegare sistematicamente.", "action_steps": ["Identifica 3-5 cose da delegare", "Per ognuna, identifica a chi e come formarli", "Inizia la prima delega"]}'::jsonb, 'Piano di delega con timeline e responsabili', ARRAY['Questo piano mi liberera tempo?', 'Ho le persone giuste?', 'Cosa faro con il tempo liberato?'], 'Se non hai creato il piano, la resistenza e pratica o emotiva?');

-- Settimana 47: Resilienza (secondo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (47, 'Il Kit di Resilienza', 'Resilienza', 'resilienza', 'Adaptation', 'integrazione', 'avanzato', 'Q4', 40, 'La resilienza si costruisce prima che serva. Questa settimana creerai il tuo kit di resilienza personale.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi si prepara alle difficolta", "prompt": "Cosa ti ha aiutato a superare le difficolta passate?", "instructions": "Pensa a tutte le risorse che hai usato: persone, pratiche, mentalita."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Le tue risorse di resilienza", "prompt": "Quali risorse hai sempre a disposizione e quali devi cercare?", "guiding_questions": ["Hai persone su cui contare?", "Hai pratiche che ti ricaricano?", "Hai una mentalita che ti sostiene?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Costruire il kit", "prompt": "Crea e documenta il tuo kit di resilienza.", "action_steps": ["Lista di persone da chiamare", "Lista di pratiche che ti ricaricano", "Frasi o principi che ti sostengono"]}'::jsonb, 'Documento con il tuo kit di resilienza', ARRAY['Il kit e completo?', 'Lo usero quando serve?', 'Cosa manca che dovrei costruire?'], 'Se non hai creato il kit, fallo quando hai energia.');

-- Settimana 48: Sviluppo Team (secondo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (48, 'Successione', 'Sviluppo Team', 'sviluppo-team', 'Adaptation', 'integrazione', 'avanzato', 'Q4', 45, 'Un leader forte costruisce altri leader. Questa settimana penserai alla successione.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi costruisce il futuro", "prompt": "Se dovessi assentarti per 3 mesi, chi potrebbe prendere il tuo posto?", "instructions": "Rispondi onestamente. Non chi vorresti, ma chi realmente potrebbe."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Quanto sei sostituibile", "prompt": "Cosa solo tu sai fare che altri dovrebbero imparare?", "guiding_questions": ["Ci sono conoscenze solo nella tua testa?", "Ci sono relazioni che solo tu gestisci?", "Ci sono decisioni che solo tu puoi prendere?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Piano di successione", "prompt": "Inizia a rendere qualcuno capace di sostituirti.", "action_steps": ["Identifica la persona con piu potenziale", "Scegli UNA cosa critica da trasferire", "Inizia il trasferimento"]}'::jsonb, 'Piano di successione iniziale', ARRAY['Quanto sono lontano dall''essere sostituibile?', 'Come mi sento a pensare alla sostituibilita?', 'Questo rende il business piu forte?'], 'Se non hai iniziato, nota la resistenza.');

-- Settimana 49: Ascolto (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (49, 'Ascoltare il Mercato', 'Ascolto', 'ascolto', 'Relations', 'integrazione', 'avanzato', 'Q4', 45, 'L''ascolto del leader va oltre le persone - include il mercato, i trend, i segnali deboli. Questa settimana espanderai il tuo ascolto.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi ascolta l''ambiente", "prompt": "Come ascolti cio che succede fuori dalla tua organizzazione?", "instructions": "Pensa a come raccogli informazioni su mercato, concorrenti, trend."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "I tuoi canali di ascolto", "prompt": "Quali canali usi e quali ignori?", "guiding_questions": ["Parli direttamente con i clienti?", "Monitori i concorrenti?", "Segui i trend del settore?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Espandere l''ascolto", "prompt": "Aggiungi un nuovo canale di ascolto.", "action_steps": ["Identifica un canale che ignori", "Dedicagli tempo questa settimana", "Nota cosa impari"]}'::jsonb, 'Descrizione del nuovo canale e degli insight', ARRAY['Cosa ho scoperto?', 'Questo canale merita tempo regolare?', 'Quali altri canali esplorare?'], 'Se non hai esplorato nuovi canali, e questione di tempo o abitudine?');

-- Settimana 50: Decisionalita (terzo passaggio)
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (50, 'Il Tuo Framework Decisionale', 'Decisionalita', 'decisionalita', 'Action', 'integrazione', 'avanzato', 'Q4', 45, 'I migliori decisori hanno un processo. Questa settimana codificherai il tuo framework decisionale.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il decisore consapevole", "prompt": "Come prendi le tue decisioni migliori?", "instructions": "Pensa alle decisioni di cui sei piu soddisfatto. Cosa avevano in comune?"}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Il tuo processo implicito", "prompt": "Quali passi segui quando decidi bene?", "guiding_questions": ["Raccogli informazioni o decidi d''istinto?", "Consulti altri o decidi da solo?", "Dormi sulle decisioni importanti?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Framework esplicito", "prompt": "Codifica il tuo framework decisionale.", "action_steps": ["Scrivi i passi che segui nelle decisioni migliori", "Aggiungi checklist per evitare errori", "Testa il framework su una decisione reale"]}'::jsonb, 'Documento con il tuo framework decisionale', ARRAY['Il framework cattura come decido davvero?', 'Lo usero?', 'Cosa manca?'], 'Se non hai codificato il framework, inizia con 3-5 punti.');

-- Settimana 51: Integrazione Generale
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (51, 'Il Tuo Anno di Leadership', 'Autoconsapevolezza', 'autoconsapevolezza', 'Vision', 'integrazione', 'avanzato', 'Q4', 60, 'Dopo 51 settimane di lavoro, e tempo di guardare indietro e integrare. Questa settimana rifletterai sul tuo percorso.', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Il leader che sei diventato", "prompt": "Rileggi i tuoi appunti dall''inizio dell''anno. Come sei cambiato?", "instructions": "Prenditi tempo per rileggere i deliverable delle settimane passate."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "I tuoi pattern di crescita", "prompt": "Quali caratteristiche sono cresciute di piu? Quali meno?", "guiding_questions": ["Dove hai fatto piu progressi?", "Dove hai faticato di piu?", "Cosa ti ha sorpreso di te stesso?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Bilancio dell''anno", "prompt": "Scrivi un bilancio del tuo anno di leadership.", "action_steps": ["Per ogni pilastro, nota un successo e un''area di miglioramento", "Identifica le 3 lezioni piu importanti", "Ringrazia te stesso per il lavoro fatto"]}'::jsonb, 'Documento di bilancio dell''anno', ARRAY['Sono soddisfatto del percorso?', 'Cosa faro diversamente l''anno prossimo?', 'Di cosa sono piu orgoglioso?'], 'Se non hai fatto il bilancio completo, anche una riflessione parziale ha valore.');

-- Settimana 52: Pianificazione Futura
INSERT INTO exercises_v2 (week_number, title, subtitle, characteristic_slug, pillar, exercise_type, difficulty_level, quarter, estimated_time_minutes, intro_validante, phase_1_recognition, phase_2_pattern, phase_3_expansion, deliverable, reflection_prompts, failure_response) VALUES (52, 'Il Leader del Futuro', 'Visione', 'visione', 'Vision', 'integrazione', 'avanzato', 'Q4', 60, 'L''ultimo esercizio guarda avanti. Che tipo di leader vuoi essere nel prossimo anno?', '{"title": "Riconoscimento - Chi Eri", "being_focus": "Chi sei diventato, chi vuoi essere", "prompt": "Basandoti sul bilancio, quale versione di te stesso vuoi far emergere?", "instructions": "Non pensare a cosa fare - pensa a chi essere."}'::jsonb, '{"title": "Pattern - Cosa Facevi", "doing_focus": "Cosa serve per diventare quel leader", "prompt": "Cosa deve cambiare per diventare la versione migliore di te?", "guiding_questions": ["Quali abitudini devi costruire?", "Quali devi abbandonare?", "Quali relazioni devi coltivare?"]}'::jsonb, '{"title": "Espansione - Come Ricreare", "having_focus": "Impegni per il nuovo anno", "prompt": "Scrivi i tuoi impegni di leadership per l''anno che viene.", "action_steps": ["Scegli 3 aree di focus per l''anno prossimo", "Per ognuna, definisci un impegno concreto", "Condividi gli impegni con qualcuno"]}'::jsonb, 'Documento di impegni di leadership per il nuovo anno', ARRAY['Questi impegni mi entusiasmano?', 'Sono realistici?', 'Come mi assicurero di mantenerli?'], 'Se non hai definito impegni, torna a questo esercizio quando sei pronto.');
